openapi: 3.0.1
info:
  title: This is an sample swagger for Java Skeleton
  version: v1.0.0
paths:
  /users:
    get:
      tags:
        - User
      operationId: getAll
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      tags:
        - User
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestNewUser'
        required: true
      responses:
        '201':
          description: Created
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/User'
  /users/{id}:
    delete:
      tags:
        - User
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '204':
          description: No Content
components:
  schemas:
    User:
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
    RequestNewUser:
      required:
        - name
      type: object
      properties:
        name:
          type: string
